name: Sync Submodules from Main

on:
  repository_dispatch:
    types: [submodule-main-updated]
  push:
    branches:
      - main

jobs:

  sync:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout main repository
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.PAT_TOKEN }}
        submodules: recursive
        
    - name: Configure Git
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        
    - name: Update submodules from main
      run: |
        git submodule update --remote
        for submodule in $(git submodule status | awk '{print $2}')
        do
          echo "Entering '$submodule'" >> "$submodule-changes.txt"
          (cd "$submodule" && git log -1 --pretty=format:"- %s (%an)") >> "$submodule-changes.txt"
        done
        if [[ -n $(git status --porcelain) ]]; then
          git add .
          git commit -F MITP-backend-changes.txt -F MITP-frontend-changes.txt -F MITP-mobile-changes.txt -m "Update submodules"
          git push
        else
          echo "No changes to sync"
          exit 0
        fi